environment:
  matrix:
    - platform: x64
      CONDAPATH: C:\Miniconda-x64
      PYVER: 3.5

    - platform: x86
      CONDAPATH: C:\Miniconda
      PYVER: 3.5

build_script:
  - '%CONDAPATH%\Scripts\conda config --set always_yes yes'
  - '%CONDAPATH%\Scripts\conda update conda'
  - '%CONDAPATH%\Scripts\conda create -p C:\pythontest python=%PYVER%'
  - '%CONDAPATH%\Scripts\activate C:\pythontest'
  - '%CONDAPATH%\Scripts\conda install -y numpy scipy'
  - '%CONDAPATH%\Scripts\conda install -y pytorch cpuonly -c pytorch'
  - '%CONDAPATH%\Scripts\conda install -y tensorflow -c conda-forge'
  - '%CONDAPATH%\Scripts\conda install -y pytest'
  - where python
  - python setup.py install

test_script:
  - pytest