matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: "3.5"
  - os: linux
    dist: xenial
    language: python
    python: "3.6"
  - os: linux
    dist: xenial
    language: python
    python: "3.7"
  - os: linux
    dist: bionic
    language: python
    python: "3.5"
  - os: linux
    dist: bionic
    language: python
    python: "3.6"
  - os: linux
    dist: bionic
    language: python
    python: "3.7"

before_install:
  - sudo apt-get install liblapack-dev;

install:
  - pip install --upgrade pip
  - pip install tensorflow pytest flake8 jupyter matplotlib
  - pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install .

script:
  - pytest
  - flake8 cvxpylayers
  - jupyter nbconvert --to notebook --execute examples/torch/*.ipynb
  - jupyter nbconvert --to notebook --execute examples/tensorflow/*.ipynb

notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com