matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: "3.5"
  - os: linux
    dist: xenial
    language: python
    python: "3.6"
  - os: linux
    dist: xenial
    language: python
    python: "3.7"
  - os: linux
    dist: bionic
    language: python
    python: "3.5"
  - os: linux
    dist: bionic
    language: python
    python: "3.6"
  - os: linux
    dist: bionic
    language: python
    python: "3.7"

before_install:
  - sudo apt-get install liblapack-dev
  - sudo apt-get install ffmpeg

install:
  - pip install --upgrade pip
  - pip install tensorflow pytest flake8 jupyter matplotlib sklearn tqdm
  - pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install .

script:
  - pytest
  - flake8 cvxpylayers
  - jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute examples/torch/data_poisoning_attack.ipynb examples/torch/convex_approximate_dynamic_programming.ipynb
  - jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute examples/tf/data_poisoning_attack.ipynb examples/tf/convex_approximate_dynamic_programming.ipynb

notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com
